# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a83cb22ade0f47b276376eaf202b2c319198ad9cca2b520326fbae072225d347c369d4acf1ec077565124fca4f593d0f42f2b08572b2c77b75230f36e0cc603f

test:
  secret_key_base: c564f07fe2a3e72e1d067a3ea27b91a62d5977a28924537e7e7c212f3bd6255f65f73ed6fa0780e71166a6792696f6d369024c36fdc020bc532d17c4bc0c5a09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
